[project]
name = "fastapiapi"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fastapi[all]>=0.115.11",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
